### ISSUE TITLE
是否可以使用代理增加vote分数

### ISSUE THREAD

**Issue by wanglz111** [dxxzst/alexamaster-autovote#1]
电脑端如果每次切换ssr，则都可以获取一次大分video
我们是否可以使用一个中间件每次完成任务后自动切换代理
模式：
run->if vote point<5 ->next proxy ->run
中间件 test proxy (if delay<*ms) ->proxy pool
                                          >*ms  ->test next proxy

**Comment by dxxzst** [comment]
@wanglz111 直接调用系统运行着的ssr切换代理不太现实。
puppeteer也支持使用代理，但只支持普通的HTTP、HTTPS、Socks等形式的代理，不支持ssr形式。
建议你还是手动切换吧
