### ISSUE TITLE
 captcha checkcode failed?

### ISSUE THREAD

**Issue by fengzhishang20** [dxxzst/alexamaster-autovote#3]
login success
2019-09-20 08:18:49 error happened in loopRun:Evaluation failed: TypeError: Cannot read property 'scrollHeight' of undefined
    at __puppeteer_evaluation_script__:3:48

**Comment by liufitch** [comment]
解决了吗？ 我也遇到这个问题

**Comment by dxxzst** [comment]
@fengzhishang20 @liufitch 因为加了验证码，所以登陆失效了。主刷程序还是正常的。
可以在windows系统中运行，将run.js中的headless: true改为headless: false，手动输入验证码

**Comment by zaoqi** [comment]
有其他方法吗

**Comment by zaoqi** [comment]
有其他方法吗？比如保存cookie？

**Comment by zaoqi** [comment]
@dxxzst
> @fengzhishang20 @liufitch 因为加了验证码，所以登陆失效了。主刷程序还是正常的。
> 可以在windows系统中运行，将run.js中的headless: true改为headless: false，手动输入验证码
Archlinux改为headless: false后还是会出现这个错误

**Comment by zaoqi** [comment]
@dxxzst
> @fengzhishang20 @liufitch 因为加了验证码，所以登陆失效了。主刷程序还是正常的。
> 可以在windows系统中运行，将run.js中的headless: true改为headless: false，手动输入验证码

Archlinux改为headless: false后还是会出现这个错误

**Comment by zaoqi** [comment]
这个验证码比较简单，应该能做到识别

**Comment by dxxzst** [comment]
@fengzhishang20 @liufitch @zaoqi 已经解决，可以用最新的代码。启动后终端里会显示验证码。一般第一次输入后面就不需要了
